version: '3'
services:
  app:
    image: cicd
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # - MONGODB_USERNAME
      # - MONGODB_PASSWORD
      # - MONGODB_DATABASE
      - MONGODB_CONNECTION_STRING=mongodb://mongo/runTheWorld
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/src
  mongo:
    image: mongo
